config/routes.rb
Rails.application.routes.draw do
  root 'application#index'
  resources :reader_books
  resources :books
  resources :authors
  resources :readers
  resources :sessions, only: [:create, :destroy]
  # get '/login' => 'sessions#new'
  # post '/login' => 'sessions#create'

  get '/sessions/new', to: 'sessions#new', as: '/login'
  post '/sessions/new', to: 'sessions#create', as: '/logged_in'
  
  # get 'login' => 'sessions#new'
  # post '/login' => 'sessions#create'
  # post '/logout' => 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reader.rb
class Reader < ApplicationRecord
    has_many :reader_books
    has_many :books, through: :reader_books

    validates :name, presence: true, uniqueness: true, length: {in: 2..15}, :format => { :with => /\A(?=.*[a-z])[a-z\d]+\Z/i }
    has_secure_password

    def self.alphabetical
        Reader.all.sort_by { |reader| reader.name }
    end

    def alpha_books
        reader.books.alphabetize
    end

    def authors
        self.books.map do |book|
            Author.find(book.author_id)
        end
    end

    def reader_diversity
        div_hash = Author.diversity_hash
        
        ### Update Gender Values ###
        gender_ary = self.authors.map do |author|
            author.gender
        end

        gender_ary.each do |gender|
            if div_hash[:gender].keys.include? gender
                div_hash[:gender][gender] += 1
            else
                    puts "There's been an error in the reader_diversity method in reader.rb."
            end
        end

        ### Update SO Values ###
        so_ary = self.authors.map do |author|
            author.sexual_orientation
        end

        so_ary.each do |so|
            if div_hash[:sexual_orientation].keys.include? so
                div_hash[:sexual_orientation][so] += 1
            else
                    puts "There's been an error in the reader_diversity method in reader.rb."
            end
        end

        ### Update Race Values ###
        race_ary = self.authors.map do |author|
            author.race
        end

        race_ary.each do |race|
            if div_hash[:race].keys.include? race
                div_hash[:race][race] += 1
            else
                    puts "There's been an error in the reader_diversity method in reader.rb."
            end
        end

        ### Update Nationality Values ###
        nation_ary = self.authors.map do |author|
            author.nationality
        end

        nation_ary.each do |nation|
            if div_hash[:nationality].keys.include? nation
                div_hash[:nationality][nation] += 1
            else
                    puts "There's been an error in the reader_diversity method in reader.rb."
            end
        end
    
        return div_hash
    end

end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController
    before_action :require_logged_in, only: [:edit, :update]

    def index
        @readers = Reader.alphabetical
    end

    def show
        @reader = Reader.find(params[:id])
    end

    def new
        @reader = Reader.new
    end

    def create
        @reader = Reader.new(reader_params)
        if @reader.valid?
            @reader.save
            redirect_to reader_path(@reader)
        else
            render :new
        end
    end

    def edit
        @reader = Reader.find(params[:id])
    end

    def update
        @reader = Reader.find(params[:id])
        @reader.update(reader_params)

        if @reader.valid?
            redirect_to reader_path(@reader)
        else
            render :edit
        end
    end

    def delete
    end


    private
    def reader_params
        params.require(:reader).permit(:name, :password, :password_digest)
    end
end

app/helpers/readers_helper.rb
module ReadersHelper
end

app/views/readers/_form.html.erb
<% if @reader.errors.any? %>
    <div id="error_explanation">
        <h2>Errors:</h2>
        <ul>
            <% @reader.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<%= form_for @reader do |f| %>
<label>Name:</label><br>
    <%= f.text_field :name %><br>

<%= submit_tag "Submit", class: 'submit_button' %>
<% end %>

app/views/readers/edit.html.erb
<h1>Edit Your Reader Account</h1>

<%= form_for @reader do |f| %> 
  <%= render 'form' %>
<% end %>

app/views/readers/index.html.erb
<body>
    <div class="page_padding">    
        <h1>Reader Index</h1>
            <ul>
                <% @readers.each do |reader| %>
                    <li>
                        <%= link_to "#{reader.name}", reader_path(reader.id) %>
                    </li>
                <% end %>
            </ul>
    </div>
</body>

app/views/readers/new.html.erb
<body>
  <div class="page_padding">  
    <h1>Create a Reader Account</h1>
      <%= form_for @reader do |f| %>
        <label> Name: </label>
          <%= f.text_field :name %></br>
        <label> Password: </label>
          <%= f.password_field :password_digest %></br>
        <label> Password Confirmation: </label>
          <%= f.password_field :password_digest, confirmation: true %><br></b>
        <%= f.submit "Submit", class: 'submit_button' %>
      <% end %>
  </div>
</body>

app/views/readers/show.html.erb
<body>
<div class="page_padding">
<div class="container">
    <div class="top">
            <h1><%= @reader.name %></h1>
                <div class="edit"><%= link_to "Edit", edit_reader_path(@reader.id) %></div>

            <h2>Diversity Statistics</h2>
                <% if @reader.books.empty? %>
                    <p>You don't have any statistics yet!</p>
                <% else %>
    </div>
                
        
    <div class="gender">
        <div class="card">
            <div class="card-container">
                
                <h3>Gender</h3>
                    <ul>
                        <% @reader.reader_diversity[:gender].each do |gender| %>
                            <li><b><%= gender[0] %>: </b><%= number_to_percentage((gender[1] * 100 / @reader.authors.count), precision: 2) %></li>
                        <% end %>
                    </ul>
            
            </div>
        </div>
    </div>    

    <div class="so">
        <div class="card">
            <div class="card-container">

                <h3>Sexual Orientation</h3>
                    <ul>
                        <% @reader.reader_diversity[:sexual_orientation].each do |so| %>
                            <li><b><%= so[0] %>: </b><%= number_to_percentage((so[1] * 100 / @reader.authors.count), precision: 2) %></li>
                        <% end %>
                    </ul>

            </div>
        </div>
    </div>

    <div class="race">
        <div class="card">
            <div class="card-container">

                <h3>Race</h3>
                    <ul>
                        <% @reader.reader_diversity[:race].each do |race| %><li>
                                <b><%= race[0] %>: </b><%= number_to_percentage((race[1] * 100 / @reader.authors.count), precision: 2) %></li>
                        <% end %>
                    </ul>

            </div>
        </div>
    </div>
        
    <div class="nationality">
        <div class="card">
            <div class="card-container">
                
                <h3>Nationality</h3>
                    <ul>
                        <% @reader.reader_diversity[:nationality].each do |nationality| %><li>
                                <b><%= nationality[0] %>: </b><%= number_to_percentage((nationality[1] * 100 / @reader.authors.count), precision: 2) %></li>
                        <% end %>
                    </ul>

            </div>
        </div>
    </div>

    <div class="bottom">
        <h2>Books</h2>
            <div class="edit"><%= link_to "Add a Book", new_reader_book_path %></div>
            
            <ul>
                <% @reader.books.alphabetical.each do |book| %>
                    <li><%= link_to book.title, book_path(book.id) %> by <%= link_to book.author.name, author_path(book.author.id) %></li>
                <% end %>
            </ul>
    
    </div>

                <% end %>
</div>
</div>
</body>