config/routes.rb
Rails.application.routes.draw do
  root 'application#index'
  resources :reader_books
  resources :books
  resources :authors
  resources :readers
  resources :sessions, only: [:create, :destroy]
  # get '/login' => 'sessions#new'
  # post '/login' => 'sessions#create'

  get '/sessions/new', to: 'sessions#new', as: '/login'
  post '/sessions/new', to: 'sessions#create', as: '/logged_in'
  
  # get 'login' => 'sessions#new'
  # post '/login' => 'sessions#create'
  # post '/logout' => 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books

    validates :last_name, :first_name, :gender, :sexual_orientation, :race, :nationality, presence: true

    def self.by_last
        Author.all.sort_by { |author| author.last_name }
    end

    def name
        self.first_name + " " + self.last_name
    end

    def alpha_books
        Book.where(author_id: self.id).alphabetical
    end

    def self.gender_ary
        gender_ary = []
        Author.all.each do |author|
            if gender_ary.exclude? author.attributes.values[3]
                gender_ary << author.attributes.values[3]
            end
        end
        gender_ary
    end

    def self.so_ary
        so_ary = []
        Author.all.each do |author|
            if so_ary.exclude? author.attributes.values[4]
                so_ary << author.attributes.values[4]
            end
        end
        so_ary
    end

    def self.race_ary
        race_ary = []
        Author.all.each do |author|
            if race_ary.exclude? author.attributes.values[5]
                race_ary << author.attributes.values[5]
            end
        end
        race_ary
    end

    def self.nation_ary
        nation_ary = []
        Author.all.each do |author|
            if nation_ary.exclude? author.attributes.values[6]
                nation_ary << author.attributes.values[6]
            end
        end
        nation_ary
    end

    def self.diversity_hash
        @diversity_hash = {
            gender: {},
            sexual_orientation: {},
            race: {},
            nationality: {}
        }

        Author.gender_ary.each do |gender|
            @diversity_hash[:gender][gender] = 0
        end
        
        Author.so_ary.each do |so|
            @diversity_hash[:sexual_orientation][so] = 0
        end

        Author.race_ary.each do |race|
            @diversity_hash[:race][race] = 0
        end

        Author.nation_ary.each do |nation|
            @diversity_hash[:nationality][nation] = 0
        end

        @diversity_hash
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    def index
        @authors = Author.by_last
    end

    def show
        @author = Author.find(params[:id])
    end

    def new
        @author = Author.new
    end

    def create
        @author = Author.new(author_params)        
        if @author.valid?
            @author.save
            redirect_to author_path(@author)
        else
            render :new
        end
    end

    def edit
        @author = Author.find(params[:id])
    end

    def update
        @author = Author.find(params[:id])
        @author.update(author_params)
        
        if @author.valid?
            redirect_to author_path(@author)
        else
            render :edit
        end
    end

    def delete
    end


    private
    def author_params
        params.require(:author).permit(:last_name, :first_name, :gender, :sexual_orientation, :race, :nationality)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<% if @author.errors.any? %>
    <div id="error_explanation">
        <h2>Errors:</h2>
        <ul>
            <% @author.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<%= form_for @author do |f| %>
<label>Last Name:</label><br>
    <%= f.text_field :last_name %><br>
 
<label>First Name:</label><br>
    <%= f.text_field :first_name %><br>

<label>Gender:</label><br>
    <%= f.text_field :gender %><br>

<label>Sexual Orientation:</label><br>
    <%= f.text_field :sexual_orientation %><br>

<label>Race:</label><br>
    <%= f.text_field :race %><br>

<label>Nationality:</label><br>
    <%= f.text_field :nationality %><br>

<%= submit_tag "Submit", class: 'submit_button' %>

<% end %>

app/views/authors/edit.html.erb
<body>
  <div class="page_padding">
    <h1>Edit an Author</h1>
      <%= render 'form' %>
  </div>
</body>

app/views/authors/index.html.erb
<body>
    <div class="page_padding">
        <h1>Author Index</h1>
            <ul>
                <% @authors.each do |author| %>
                    <li>
                        <%= link_to "#{author.last_name}, #{author.first_name}", author_path(author.id) %>
                    </li>
                <% end %>
            </ul>
    </div>
</body>

app/views/authors/new.html.erb
<body>
    <div class="page_padding">
        <h1>Submit a New Author</h1>
            <%= render 'form' %>
    </div>
</body>

app/views/authors/show.html.erb
<body>
    <div class="page_padding">
        <h1><%= @author.name %></h1>
            <h2>Information</h2>
                <div class="edit"><%= link_to "Edit", edit_author_path(@author.id) %></div>
                    <ul>
                        <li>
                            <b>Gender: </b><%= @author.gender %>
                        </li>
                        <li>
                            <b>Sexual Orientation: </b><%= @author.sexual_orientation %>
                        </li>
                        <li>
                            <b>Race: </b><%= @author.race %>
                        </li>
                        <li>
                            <b>Nationality: </b><%= @author.nationality %>
                        </li>
                    </ul>

            <h2>Books</h2>
                <div class="edit"><%= link_to "Add a book", new_book_path %></div>

                <ul>
                    <% @author.alpha_books.each do |book| %>
                        <li>
                            <%= link_to book.title, book_path(book.id) %>
                        </li>
                    <% end %>
                </ul>
    </div>
</body>