config/routes.rb
Rails.application.routes.draw do
  root 'application#index'
  resources :reader_books
  resources :books
  resources :authors
  resources :readers
  resources :sessions, only: [:create, :destroy]
  # get '/login' => 'sessions#new'
  # post '/login' => 'sessions#create'

  get '/sessions/new', to: 'sessions#new', as: '/login'
  post '/sessions/new', to: 'sessions#create', as: '/logged_in'
  
  # get 'login' => 'sessions#new'
  # post '/login' => 'sessions#create'
  # post '/logout' => 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :author
    has_many :reader_books
    has_many :readers, through: :reader_books

    validates :title, presence: true
    validates :author_id, presence: true
    validate :author_id_exists

    def author_id_exists
        return false if Author.find_by_id(self.author_id).nil?
    end

    # Moves articles ("a," "an," and "the") to the end of a title, appending it with a comma; returns all objects with changed titles
    def self.article_shift
        books = Book.all
        books.each do |book|
            title_ary = book.title.split(" ")
            first_word = title_ary.first
            if first_word == "A" || first_word == "An" || first_word == "The"
                title_ary.shift
                new_title = title_ary.join(" ")
                new_title = new_title + ", " + first_word
                book.title = new_title
            end
        end
    end
    
    def self.alphabetical
        Book.article_shift.sort_by do |book|
            book.title
        end
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @books = Book.alphabetical
    end

    def show
        @book = Book.find(params[:id])
    end

    def new
        @book = Book.new
    end

    def create
        @book = Book.new(
            author_id: params["author_id"],
            title: params["book"]["title"]
        )
        puts book_params
        if @book.valid?
            @book.save
            redirect_to book_path(@book)
        else
            render :new
        end
    end

    def edit
        @book = Book.find(params[:id])
    end

    def update
        @book = Book.find(params[:id])
        @book.update(
            author_id: params["author_id"],
            title: params["book"]["title"]
        )

        if @book.valid?
            redirect_to book_path(@book)
        else
            render :edit
        end
    end

    def delete
    end


    private
    def book_params
        params.require(:book).permit(:title, :author_id)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<% if @book.errors.any? %>
    <div id="error_explanation">
        <h2>Errors:</h2>
        <ul>
            <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<%= form_for @book do |f| %>
<label>Title:</label><br>
    <%= f.text_field :title %><br>
 
<label>Author:</label><br> <select name="author_id">
            <% Author.by_last.each do |author| %>
                
                <% if @book.author_id == author.id %>

                    <option selected value="<%= author.id %>">
                        <%= author.last_name + ", " + author.first_name %>
                    </option>
                <% else %>
                    <option value="<%= author.id %>">
                        <%= author.last_name + ", " + author.first_name %>
                    </option>
                <% end %>
            <% end %>
        </select>

<%= submit_tag "Submit", class: 'submit_button' %>

<% end %>

app/views/books/edit.html.erb
<body>
    <div class="page_padding">
        <h1>Edit a Book</h1>
            <%= render 'form' %>
    </div>
</body>

app/views/books/index.html.erb
<body>
    <div class="page_padding">
        <h1>Browse Books</h1>
            <ul>
                <% @books.each do |book| %>
                    <li>
                        <%= link_to "#{book.title}", book_path(book.id) %>
                    </li>
                <% end %>
            </ul>
    </div>
</body>

app/views/books/new.html.erb
<h1>Submit a New Book</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<body>
    <div class="page_padding">
        <h1><%= @book.title %></h1>
            <h2>Information</h2>
                <div class="edit"><%= link_to "Edit", edit_book_path(@book.id) %></div>

            <p>Author: <%= link_to "#{@book.author.name}", author_path(@book.author.id) %>
    </div>
</body>