config/routes.rb
Rails.application.routes.draw do
  root 'application#index'
  resources :reader_books
  resources :books
  resources :authors
  resources :readers
  resources :sessions, only: [:create, :destroy]
  # get '/login' => 'sessions#new'
  # post '/login' => 'sessions#create'

  get '/sessions/new', to: 'sessions#new', as: '/login'
  post '/sessions/new', to: 'sessions#create', as: '/logged_in'
  
  # get 'login' => 'sessions#new'
  # post '/login' => 'sessions#create'
  # post '/logout' => 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Read Diversely</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
      @import url('https://fonts.googleapis.com/css?family=Lato:light,bold|Roboto+Slab&display=swap');
    </style>

  </head>
  
  <body>
    <ul class="h">
      <li class="h"><%= link_to "Read Diversely", '/' %></li>

      <li class ="dropdown">
        Authors
        <%# <a href="javascript:void(0)" class="dropbtn">Authors</a> %>
        <div class="dropdown-content">
          <%= link_to "View All", authors_path(@authors) %>
          <%= link_to "Create New", new_author_path(@authors) %>
        </div>
      </li>

      <li class ="dropdown">
        <%# <a href="javascript:void(0)" class="dropbtn">Books</a> %>
        Books
        <div class="dropdown-content">
          <%= link_to "View All", books_path(@books) %>
          <%= link_to "Create New", new_book_path(@books) %>
        </div>
      </li>

      <% if session[:id] %>
          <li class ="dropdown">
          <%# <a href="javascript:void(0)" class="dropbtn">Readers</a> %>
          Readers
          <div class="dropdown-content">
            
            <%= link_to "Dashboard", reader_path(session[:id]) %>
            <%= link_to "Log Out", session_path(session[:id]), method: :delete, :data => { :confirm => "You are now logged out." }  %>
            
          </div>
        </li>
      <% else %>
        <li class ="dropdown">
          <%# <a href="javascript:void(0)" class="dropbtn">Readers</a> %>
          Readers
          <div class="dropdown-content">
            <%= link_to "Log In", login_path %>
            <%= link_to "Sign Up", new_reader_path(@readers) %>
          </div>
        </li>
      <% end %>





    </ul>








    <%= yield %>  
  </body>
</html>